# Generated by Django 5.1.1 on 2025-01-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_team_rank_alter_team_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['group', 'rank']},
        ),
    ]
