# Generated by Django 5.1.1 on 2025-01-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_populate_match_tournaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(
                null=False,  # Make it required
                on_delete=django.db.models.deletion.CASCADE,
                related_name='matches',
                to='tournament.tournament'
            ),
        ),
        migrations.DeleteModel(
            name='GroupMapping',
        ),
    ]
