# Generated by Django 5.1.1 on 2025-04-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_make_tournament_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='tournament_group',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name='teams',
                to='tournament.tournamentgroup'
            ),
        ),
    ]
