# Generated by Django 5.1.1 on 2025-04-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_ensure_tournament_group_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
