# Generated by Django 5.1.1 on 2025-09-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_team_is_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='walkover_winner',
            field=models.CharField(blank=True, choices=[(None, 'No walkover'), ('team1', 'Team 1 walkover win'), ('team2', 'Team 2 walkover win')], help_text='Indicates if this match was won by walkover due to opponent retirement', max_length=5, null=True),
        ),
    ]
