# Generated by Django 5.1.1 on 2025-09-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_add_walkover_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='walkover_winner',
        ),
        migrations.AddField(
            model_name='match',
            name='retired_team',
            field=models.CharField(blank=True, choices=[(None, 'No retirement'), ('team1', 'Team 1 retired'), ('team2', 'Team 2 retired')], help_text='Indicates which team retired from the match due to injury', max_length=5, null=True),
        ),
    ]
