# Generated by Django 5.1.1 on 2026-01-04 12:00
from django.db import migrations


def create_predefined_groups(apps, schema_editor):
    """Create predefined group names for tournament selection"""
    Group = apps.get_model('tournament', 'Group')

    # Only create groups that don't already exist
    group_names = [
        'Racketeers',
        'Serve-ivors',
        'Smashers',
        'Volleyers',
        'Lobbers',
        'Baseliners',
        'Net Rushers',
        'Groundstrokers',
    ]

    for name in group_names:
        Group.objects.get_or_create(name=name)


def reverse_migration(apps, schema_editor):
    """Remove predefined groups (only if they're not in use)"""
    Group = apps.get_model('tournament', 'Group')
    TournamentGroup = apps.get_model('tournament', 'TournamentGroup')

    # Delete groups that are not associated with any tournament
    unused_groups = Group.objects.exclude(
        id__in=TournamentGroup.objects.values_list('group_id', flat=True)
    )
    unused_groups.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_rename_walkover_to_retired'),
    ]

    operations = [
        migrations.RunPython(create_predefined_groups, reverse_migration),
    ]
