/** @type {import('tailwindcss').Config} */

const colors = require('tailwindcss/colors')
module.exports = {
  content: ["./tournament/templates/**/*.html", "./tournament/static/**/*.js"],
  theme: {
    extend: {
      colors: {
        "custom-teal": "#09c3a1",
        "custom-green": "#91c768",
        "custom-lime": "#c0dd55",
        "custom-yellow": "#eaf3a5",
        "custom-gray": "#f2f2f2",
        "custom-pink-0": "#ffc983",
        "custom-pink-1": "#ffe6ed",
        "custom-pink-2": "#f283c6",
        "custom-pink-3": "#f47c71",
        "custom-pink-4": "#ff4d85",
        "custom-pink-5": "#f36059",
        "custom-pink-6": "#f05c77",
        "custom-badge-0-0": colors.teal[100],
        "custom-badge-0-1": colors.emerald[50],
        "custom-badge-0-2": colors.cyan[200],
        "custom-badge-0-3": colors.green[100],
        "custom-badge-0-4": colors.blue[50],
        "custom-badge-0-5": colors.teal[200],
        "custom-badge-0-6": colors.lime[100],
        "custom-badge-0-7": colors.teal[50],
        "custom-badge-0-8": colors.cyan[100],
        "custom-badge-0-9": colors.emerald[100],
        "custom-badge-1-0": "#fee2e2",
        "custom-badge-1-1": "#e7e5e4",
        "custom-badge-1-2": colors.pink[50],
        "custom-badge-1-3": "#fecaca",
        "custom-badge-1-4": "#e5e5e5",
        "custom-badge-1-5": "#fef2f2",
        "custom-badge-1-6": colors.rose[200],
        "custom-badge-1-7": colors.pink[100],
        "custom-badge-1-8": colors.stone[200],
        "custom-badge-1-9": colors.rose[50],
        "tab-badge-0": colors.blue[100],
        "tab-badge-1": "#fef2f2",
        "tab-badge-2": colors.green[100],
        "tab-badge-3": colors.purple[100],
        "tab-badge-4": colors.amber[100],
      },
      fontFamily: {
        monofett: ["Monofett", "sans-serif"],
      },
    },
  },
  safelist: [
    "bg-custom-pink-0",
    "bg-custom-pink-1",
    "bg-custom-pink-2",
    "bg-custom-pink-3",
    "bg-custom-pink-4",
    "bg-custom-pink-5",
    "bg-custom-pink-6",
    "bg-custom-badge-0-0",
    "bg-custom-badge-0-1",
    "bg-custom-badge-0-2",
    "bg-custom-badge-0-3",
    "bg-custom-badge-0-4",
    "bg-custom-badge-0-5",
    "bg-custom-badge-0-6",
    "bg-custom-badge-0-7",
    "bg-custom-badge-0-8",
    "bg-custom-badge-0-9",
    "bg-custom-badge-1-0",
    "bg-custom-badge-1-1",
    "bg-custom-badge-1-2",
    "bg-custom-badge-1-3",
    "bg-custom-badge-1-4",
    "bg-custom-badge-1-5",
    "bg-custom-badge-1-6",
    "bg-custom-badge-1-7",
    "bg-custom-badge-1-8",
    "bg-custom-badge-1-9",
    "bg-tab-badge-0",
    "bg-tab-badge-1",
    "bg-tab-badge-2",
    "bg-tab-badge-3",
    "bg-tab-badge-4",
    ],
  plugins: [],
};
